// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPSbdNyOo6Vz3JC9X0FTSec-ODhSnmiiY',
    appId: '1:9235066867:web:7c5f1fa9f62e81e5b92c86',
    messagingSenderId: '9235066867',
    projectId: 'nota-f7e21',
    authDomain: 'nota-f7e21.firebaseapp.com',
    storageBucket: 'nota-f7e21.firebasestorage.app',
    measurementId: 'G-HJRPMK6L3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvN-yargR9P6aPPsPnBLn3T4NfVEiDfUs',
    appId: '1:9235066867:android:9bc9504879aba292b92c86',
    messagingSenderId: '9235066867',
    projectId: 'nota-f7e21',
    storageBucket: 'nota-f7e21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDzoLK-ykCdHpu-y-Wet9sf6Qq2CAao2s',
    appId: '1:9235066867:ios:82cd03a9519c5ad2b92c86',
    messagingSenderId: '9235066867',
    projectId: 'nota-f7e21',
    storageBucket: 'nota-f7e21.firebasestorage.app',
    iosClientId: '9235066867-3s693c1ing127l5elbsmi9pnraf2bi04.apps.googleusercontent.com',
    iosBundleId: 'com.example.nota',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDzoLK-ykCdHpu-y-Wet9sf6Qq2CAao2s',
    appId: '1:9235066867:ios:82cd03a9519c5ad2b92c86',
    messagingSenderId: '9235066867',
    projectId: 'nota-f7e21',
    storageBucket: 'nota-f7e21.firebasestorage.app',
    iosClientId: '9235066867-3s693c1ing127l5elbsmi9pnraf2bi04.apps.googleusercontent.com',
    iosBundleId: 'com.example.nota',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPSbdNyOo6Vz3JC9X0FTSec-ODhSnmiiY',
    appId: '1:9235066867:web:4d30b5e8fef2183eb92c86',
    messagingSenderId: '9235066867',
    projectId: 'nota-f7e21',
    authDomain: 'nota-f7e21.firebaseapp.com',
    storageBucket: 'nota-f7e21.firebasestorage.app',
    measurementId: 'G-DB40HCNSX1',
  );
}
